export const slides = {
  slide1: "/slide1.svg",
  developer1: "/developer1.svg",
  developer2: "/developer2.svg",
  CEO: "/photo_2020-08-15 20.15.45.png",
  CTO: "/photo_2020-08-15 20.18.02.png",
  CPM: "/cpm.png",
  LeftBlueVector: "/leftVectorTestimonials.svg",
  LeftVector: "/leftVector.svg",
  RightVector: "/rightVector.svg",
  RightBlueVector: "/rightBlueVector.svg",
  clientSpain: "/client.svg",
  flagSpain: "/spainFlag.png",
  indiaFlag: "/indiaFlag.jpg",
  americaFlag: "/americaFlag.png",
  unknown: "/unknown.png",
  AdminVectorRight: "/rightAdminVector.svg",
  AdminVectorLeft: "/LeftAdminVector.svg",
  Check: "/Check.svg",
  deleteIcon: "/deleteIcon.svg",
};

export const portfolioSlides = {
  project1: "/project1.png",
  project2: "/project2.png",
  project3: "/project3.png",
  project4: "/project4.png",
  project5: "/project5.png",
  project6: "/project6.png",
  project7: "/project7.png",
};
